services:

  customerdb:
    image: postgres
    container_name: customerdb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=customerdb
    volumes:
      - customerdb:/var/lib/postgresql/data
    networks:
      - udemy
  
  catalogdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: catalogdb
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=YourStrong!Pass123
     - MSSQL_PID=Developer
    ports:
     - "1435:1433"
    volumes:
     - catalogdb:/var/opt/mssql
    networks:
     - udemy
  
  basketdb:
    image: redis:7.2
    container_name: basketdb
    ports:
     - "6390:6379"
    volumes:
     - basketdb:/data
    command : ["redis-server","--appendonly","yes"]
    networks:
     - udemy
  
  salesdb:
    image: mongo
    container_name: salesdb
    ports:
     - "27017:27017"
    volumes:
     - "salesdb:/data/db/"
    networks:
     - udemy
  
  invoicedb:
    image: postgres
    container_name: invoicedb  
    ports:
     - "5434:5432"
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=123456
     - POSTGRES_DB=invoicedb
    networks:
     - udemy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - udemy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - udemy
  
  # message broker  
  rabbitmq:
   image: rabbitmq:3.13-management
   container_name: rabbitmq
   hostname: rabbitmq
   ports:
    - "5672:5672"
    - "15672:15672"
   environment:
    RABBITMQ_DEFAULT_USER : admin
    RABBITMQ_DEFAULT_PASS : admin123
   volumes:
    - rabbitmq_data:/var/lib/rabbitmq
   networks:
    - udemy

volumes:
  customerdb:
  esdata:
  rabbitmq_data:
  catalogdb:
  basketdb:
  salesdb:

networks:
  udemy:
    driver: bridge