<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Core.ElasticSearch" Version="3.0.0" />
    <PackageReference Include="Core.Security.Encryption" Version="3.0.1" />
    <PackageReference Include="Core.Security.Jwt" Version="3.0.1" />
    <PackageReference Include="Core.Security.Redis" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
	  
		  <PackageReference Include="Core.Events" Version="3.0.0" />
		  <PackageReference Include="Core.Messaging" Version="3.0.0" />
		  <PackageReference Include="Core.Messaging.Transport.RabbitMq" Version="3.0.0" />
		  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
		  
	 

  </ItemGroup>

</Project>
